[2022-07-30 23:25:58,637] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: migrate_data.create_schema_and_migrate_data scheduled__2022-07-06T02:00:00+00:00 [queued]>
[2022-07-30 23:25:58,686] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: migrate_data.create_schema_and_migrate_data scheduled__2022-07-06T02:00:00+00:00 [queued]>
[2022-07-30 23:25:58,686] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-30 23:25:58,686] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-07-30 23:25:58,686] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-30 23:25:58,698] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): create_schema_and_migrate_data> on 2022-07-06 02:00:00+00:00
[2022-07-30 23:25:58,700] {standard_task_runner.py:52} INFO - Started process 11130 to run task
[2022-07-30 23:25:58,701] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'migrate_data', 'create_schema_and_migrate_data', 'scheduled__2022-07-06T02:00:00+00:00', '--job-id', '92', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_dag_migrator.py', '--cfg-path', '/tmp/tmpjj4wq1ta', '--error-file', '/tmp/tmp3oq9d7bx']
[2022-07-30 23:25:58,702] {standard_task_runner.py:80} INFO - Job 92: Subtask create_schema_and_migrate_data
[2022-07-30 23:25:58,714] {logging_mixin.py:115} WARNING - /home/hp/miniconda3/envs/checker/lib/python3.8/site-packages/airflow/configuration.py:532 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2022-07-30 23:25:58,715] {logging_mixin.py:115} WARNING - /home/hp/miniconda3/envs/checker/lib/python3.8/site-packages/airflow/configuration.py:532 DeprecationWarning: The sql_engine_encoding option in [core] has been moved to the sql_engine_encoding option in [database] - the old setting has been used, but please update your config.
[2022-07-30 23:25:58,731] {task_command.py:371} INFO - Running <TaskInstance: migrate_data.create_schema_and_migrate_data scheduled__2022-07-06T02:00:00+00:00 [running]> on host hp-HP-Pavilion-Laptop-15-eg0xxx
[2022-07-30 23:25:58,762] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=tesfaye
AIRFLOW_CTX_DAG_ID=migrate_data
AIRFLOW_CTX_TASK_ID=create_schema_and_migrate_data
AIRFLOW_CTX_EXECUTION_DATE=2022-07-06T02:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-06T02:00:00+00:00
[2022-07-30 23:25:58,776] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/hp/miniconda3/envs/checker/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/hp/miniconda3/envs/checker/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/hp/airflow/dags/create_dag_dag_migrator.py", line 61, in start_workflow
    schema = get_schema_and_table_name(database_name)
  File "/home/hp/airflow/dags/create_dag_dag_migrator.py", line 26, in get_schema_and_table_name
    cursor.execute(query)
psycopg2.errors.UndefinedColumn: column "pg_catalog" does not exist
LINE 1: ...M information_schema.tables WHERE table_schema != "pg_catalo...
                                                             ^

[2022-07-30 23:25:58,780] {taskinstance.py:1415} INFO - Marking task as UP_FOR_RETRY. dag_id=migrate_data, task_id=create_schema_and_migrate_data, execution_date=20220706T020000, start_date=20220730T202558, end_date=20220730T202558
[2022-07-30 23:25:58,788] {standard_task_runner.py:92} ERROR - Failed to execute job 92 for task create_schema_and_migrate_data (column "pg_catalog" does not exist
LINE 1: ...M information_schema.tables WHERE table_schema != "pg_catalo...
                                                             ^
; 11130)
[2022-07-30 23:25:58,793] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-30 23:25:58,806] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
